### ISSUE TITLE
Script needs a better name

### ISSUE THREAD

**Issue by quixand** [MatthewJohn/terraform_sg_diff#2]
suggestions
Make Terraform great again
tfPrettyPrint
tfd
beautiful-terraform
TerraformDiff
keir-test
craigsBeard-ng
goodform
betterform
not-so-terrableform

**Comment by MatthewJohn** [comment]
Would terraform-test-beard suffice?

**Comment by quixand** [comment]
emma-demo

**Comment by MatthewJohn** [comment]
Closing as reporter has forgotten how to use terraform

**Comment by quixand** [comment]
How does that have anything to do with the name of the script?

**Comment by MatthewJohn** [comment]
See c9b18a0ed11b1145958c964ad598811d063161e0

**Comment by jonwsavage** [comment]
`beard-facade`

**Comment by MatthewJohn** [comment]
'apologies', nothing should ever have the name facade.. too pretentious.

**Comment by MatthewJohn** [comment]
After meeting, ideas are towards:
 * goodform
 * not-so-terrableform

**Comment by quixand** [comment]
votes for notsoterribleform or not-so-terribleform
